services:
  frontend:
    image: dij0s/petal-ui:latest
    env_file:
      - .env.${ENVIRONMENT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
  backend:
    image: dij0s/petal-backend:latest
    env_file:
      - .env.${ENVIRONMENT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      redis:
        condition: service_started
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  ollama:
    image: ollama/ollama
    restart: unless-stopped
    env_file:
      - .env.${ENVIRONMENT}
    ports:
      - ${OLLAMA_PORT}:11434
    volumes:
      - ./ollama-data:/root/.ollama
      - ./ollama-entrypoint.sh:/ollama-entrypoint.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    entrypoint: ["/bin/bash", "/ollama-entrypoint.sh"]
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
